"""Functions for training a model with dataloader"""

# Author: Peishi Jiang
# Email: shixijps@gmail.com

import jax
import optax
import equinox as eqx
import jax.numpy as jnp

from torch.utils.data import DataLoader

from typing import Callable
from jaxtyping import PyTree


def train_dl(
    model: eqx.Module, filter_model_spec: eqx.Module,
    nsteps: int, loss_func: Callable, 
    optim: optax.GradientTransformation, 
    trainloader: DataLoader, testloader: DataLoader
):
    opt_state = optim.init(eqx.filter(model, eqx.is_array))

    loss_train_set, loss_test_set = [], []
    for step in range(nsteps):
        print('\n')
        print(f'Epoch {step}\n-----')
        # Update the model on the training data
        model, opt_state, loss_value_train = train_each_step_dl(
            model, filter_model_spec, trainloader, loss_func, optim, opt_state)

        # Evaluate the model on the test data
        if testloader is not None:
            loss_value_test = evaluate_dl(model, testloader, loss_func)
            loss_train_set.append(loss_value_train)
            loss_test_set.append(loss_value_test)
        else:
            loss_train_set.append(loss_value_train)
    
    loss_train_set = jnp.array(loss_train_set)
    loss_test_set = jnp.array(loss_test_set)
    
    return model, loss_train_set, loss_test_set


def train_each_step_dl(
    model: eqx.Module, filter_model_spec: eqx.Module, trainloader: DataLoader, 
    loss_func: Callable, optim: optax.GradientTransformation, opt_state: PyTree):
    train_loss, k = 0, 0
    num_batches = len(trainloader)
    for i, (x, y) in enumerate(trainloader):
        x, y = jnp.array(x), jnp.array(y)
        model, opt_state, train_loss_each = make_step(
            model, filter_model_spec, x, y, loss_func, optim, opt_state
        )
        k += 1
        train_loss += train_loss_each
    train_loss /= num_batches
    print(f"Training loss: {train_loss}")
    return model, opt_state, train_loss


@eqx.filter_jit
def make_step(model, filter_model_spec, x, y, loss_func, optim, opt_state):
    diff_model, static_model = eqx.partition(model, filter_model_spec)
    # loss_value, grads = eqx.filter_value_and_grad(loss_func)(model, x, y)
    loss_value, grads = loss_func_optim(diff_model, static_model, x, y, loss_func)
    updates, opt_state = optim.update(grads, opt_state, model)
    # updates, opt_state = optim.update(grads, opt_state)
    model = eqx.apply_updates(model, updates)
    return model, opt_state, loss_value


@eqx.filter_value_and_grad
def loss_func_optim(diff_model, static_model, x, y, loss_func):
    """Calculating the gradient with respect to diff_model.
       Note that diff_model and static_model has the same type and
       can be generated by using the filtering strategy. See an example here:
       https://docs.kidger.site/equinox/examples/frozen_layer/.
    """
    model = eqx.combine(diff_model, static_model)
    # pred_y = model(*x)
    # pred_y = model(x)
    pred_y = jax.vmap(model)(x)
    return loss_func(y, pred_y)


def evaluate_dl(model, testloader, loss_func):
    test_loss, k = 0, 0
    num_batches = len(testloader)
    loss_func = eqx.filter_jit(loss_func)
    for i, (x, y) in enumerate(testloader):
        x, y = jnp.array(x), jnp.array(y)
        pred_y = jax.vmap(model)(x)
        test_loss_each = loss_func(y, pred_y)
        k += 1
        test_loss += test_loss_each
    
    # print(f'Test loss: {test_loss}')
    test_loss /= num_batches
    print(f'Test loss: {test_loss}')
    return test_loss


def predict_dl(data_loader, model):
    # initiaze output data
    y_pred_set = []

    # iterate through data from data loader and make prediction
    for i, (x,y) in enumerate(data_loader):
        x, y = jnp.array(x), jnp.array(y)
        y_pred = jax.vmap(model)(x)
        # y_pred_set.append(ht_pred[:,-1])
        y_pred_set.append(y_pred)
    
    return jnp.concatenate(y_pred_set, 0)

# def predict_dl(data_loader, model):
#     # initiaze output data
#     y_pred_set = []
#     yc_pred_set = []
#     ht_pred_set = []
#     ct_pred_set = []

#     # iterate through data from data loader and make prediction
#     for i, (x,y) in enumerate(data_loader):
#         x, y = jnp.array(x), jnp.array(y)
#         y_pred, yc_pred, ht_pred, ct_pred = jax.vmap(model.output_all)(x)
#         # y_pred_set.append(ht_pred[:,-1])
#         y_pred_set.append(y_pred)
#         yc_pred_set.append(yc_pred)
#         ht_pred_set.append(ht_pred)
#         ct_pred_set.append(ct_pred)
#         # y_pred_set = jnp.concatenate((y_pred_set, y_pred), 0)
    
#     return jnp.concatenate(y_pred_set, 0), \
#            jnp.concatenate(yc_pred_set, 0), \
#            jnp.concatenate(ht_pred_set, 0), \
#            jnp.concatenate(ct_pred_set, 0)