"""Functions for training."""

# Author: Peishi Jiang
# Email: shixijps@gmail.com

from torch.utils.data import DataLoader

import jax.numpy as jnp
import optax
import equinox as eqx
from tqdm import tqdm

from typing import Optional, Callable, Tuple
from jaxtyping import Array, PyTree


def train(
    model: eqx.Module, filter_model_spec: eqx.Module,
    nsteps:int, loss_func: Callable, 
    optim: optax.GradientTransformation, 
    trainloader: DataLoader, testloader: Optional[DataLoader]=None,
    *model_args,
) -> Tuple[eqx.Module, Array, Array]:
    """Function to train one model/mapping.

    Args:
        model (eqx.Module): the eqx.Module model to be trained
        filter_model_spec (eqx.Module): the corresponding filtered eqx.Module model
        nsteps (int): the number of training steps
        loss_func (Callable): the loss function
        optim (optax.GradientTransformation): the optimizer
        trainloader (BatchedDL): the training dataloader
        testloader (Optional[BatchedDL], optional): the test dataloader. Defaults to None.

    Returns:
        model: the trained model
        loss_train_set: the loss values of the train set
        loss_test_set: the loss values of the test set
    """
    opt_state = optim.init(eqx.filter(model, eqx.is_array))

    loss_train_set, loss_test_set = [], []
    for step in tqdm(range(nsteps)):
        # Update the model on the training data
        model, opt_state, loss_value_train = train_each_step(
            model, filter_model_spec, trainloader, loss_func, optim, opt_state, *model_args
        )

        # Evaluate the model on the test data
        if testloader is not None:
            loss_value_test = evaluate(model, testloader, loss_func)
            loss_train_set.append(loss_value_train)
            loss_test_set.append(loss_value_test)
        else:
            loss_train_set.append(loss_value_train)

    loss_train_set = jnp.array(loss_train_set)
    loss_test_set = jnp.array(loss_test_set) if testloader is not None else None
    
    return model, loss_train_set, loss_test_set


# @eqx.filter_jit
def train_each_step(
    model: eqx.Module, filter_model_spec: eqx.Module,
    trainloader: DataLoader, loss_func: Callable,
    optim: optax.GradientTransformation, opt_state: PyTree,
    *model_args
):
    train_loss, k = 0, 0
    for i, (x, y) in enumerate(trainloader):
        x, y = jnp.array(x), jnp.array(y)
        model, opt_state, train_loss_each = make_step(
            model, filter_model_spec, opt_state, x, y, loss_func, optim, *model_args
        )
        k += 1
        train_loss += train_loss_each
    train_loss /= k
    return model, opt_state, train_loss


@eqx.filter_jit
def make_step(
    model: eqx.Module,
    filter_model_spec: eqx.Module,
    opt_state: PyTree,
    x: Array,
    y: Array,
    loss_func: Callable,
    optim: optax.GradientTransformation,
    *args,
):
    diff_model, static_model = eqx.partition(model, filter_model_spec)
    # loss_value, grads = eqx.filter_value_and_grad(loss_func_optim)(model, x, y)
    loss_value, grads = loss_func_optim(
            diff_model, static_model, x, y, loss_func, *args
    )
    updates, opt_state = optim.update(grads, opt_state, model)
    model = eqx.apply_updates(model, updates)
    return model, opt_state, loss_value


@eqx.filter_value_and_grad
def loss_func_optim(
    diff_model: eqx.Module,
    static_model: eqx.Module,
    x: Array,
    y: Array,
    loss_func: Callable,
    *model_args,
):
    """Calculating the gradient with respect to diff_model.
       Note that diff_model and static_model has the same type and
       can be generated by using the filtering strategy. See an example here:
       https://docs.kidger.site/equinox/examples/frozen_layer/.
    """
    model = eqx.combine(diff_model, static_model)
    pred_y = model(x, *model_args)
    return loss_func(y, pred_y)


def evaluate(model: eqx.Module, testloader: DataLoader, loss_func: Callable, *model_args):
    test_loss, k = 0, 0
    loss_func = eqx.filter_jit(loss_func)
    for i, (x, y) in enumerate(testloader):
        x, y = jnp.array(x), jnp.array(y)
        pred_y = model(x, *model_args)
        test_loss_each = loss_func(y, pred_y)
        k += 1
        test_loss += test_loss_each
    test_loss /= k
    return test_loss