name: nn-flow-transport
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scipy
  - seaborn
  - scikit-learn
  - matplotlib
  - ipykernel
  - mesas
  - pip
  - pip:
    - hydroeval
    - pytest
    - jax[cuda12]
    - optax
    - equinox
    - tqdm
    - torch
    - torchvision
